### ISSUE TITLE
"Copy Link" on Chrome Desktop shows "copied" after clicking but fails to copy

### ISSUE THREAD

**Issue by pagameba** [farcasterxyz/auth-monorepo#175]
**What is the bug?**
A concise, high level description of the bug and how it affects you

Tested on Mac OSX Chrome, clicking the "Copy Link" button gives a visual indication that the link was copied, but there is an error in the console from the Clipboard API and the link is not copied.

**How can it be reproduced? (optional)**
Include steps, code samples, replits, screenshots and anything else that would be helpful to reproduce the problem. 

Click the "copy text" button.

log is:

```
6641.0a13e303.chunk.js:1 [Violation] Permissions policy violation: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.
onClick @ 6641.0a13e303.chunk.js:1
warpcast.com/static/js/6641.0a13e303.chunk.js:1 Uncaught (in promise) DOMException: Failed to execute 'writeText' on 'Clipboard': The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.
    at onClick (https://warpcast.com/static/js/6641.0a13e303.chunk.js:1:7088)
    at Object.Re (https://warpcast.com/static/js/main.32761306.js:1:1806650)
    at Ze (https://warpcast.com/static/js/main.32761306.js:1:1806804)
    at https://warpcast.com/static/js/main.32761306.js:1:1826704
    at Lr (https://warpcast.com/static/js/main.32761306.js:1:1826798)
    at Br (https://warpcast.com/static/js/main.32761306.js:1:1827213)
    at https://warpcast.com/static/js/main.32761306.js:1:1832655
    at uc (https://warpcast.com/static/js/main.32761306.js:1:1896367)
    at Ne (https://warpcast.com/static/js/main.32761306.js:1:1805782)
    at zr (https://warpcast.com/static/js/main.32761306.js:1:1828507)
```

**Additional context (optional)**

**Comment by AmAzing129** [comment]
Which "Copy Link" button? Could you give a photo and more details?

**Comment by pagameba** [comment]
Hm, its stopped doing it.  I'm going to assume it was something on my end.  Sorry for the noise :)
